package com.djx.i18nzeal.constants

import com.djx.i18n.runtime.export.Locale
import com.djx.i18n.runtime.interfaces.I18nEngine


/**
 * Auto generated by i18nZeal.
 * Do not edit manually.
 */
val En = Locale("en")
val Zh = Locale("zh")

object I18nKeys {
    const val app_name = "app.name"
    const val count = "count"
    const val lang_current = "lang.current"
    const val lang_en = "lang.en"
    const val lang_system = "lang.system"
    const val lang_zh = "lang.zh"
}

/**
 * Auto generated by i18nZeal.
 * Do not edit manually.
 */
object I18nZeal: I18nEngine {

    private val langMap = mapOf(
        En.code to I18nZeal_en.map,
        Zh.code to I18nZeal_zh.map,
    )

    override fun get(
        key: String?,
        locale: Locale,
        fallback: String,
        vararg args: Any?,
    ): String {

        if (key.isNullOrBlank()) return ""

        val text = langMap[locale.code]?.get(key) ?: fallback

        if (args.isEmpty()) return text
        if (!text.contains("{")) return text

        return format(text, *args)
    }

    private fun format(
        text: String,
        vararg args: Any?
    ): String {
        var result = text

        args.forEachIndexed { index, value ->
            result = result.replace(
                oldValue = "{$index}",
                newValue = value?.toString().orEmpty()
            )
        }

        return result
    }
}

object I18nZeal_en {
    val map = mapOf(
        "app.name" to "i18nZeal",
        "count" to "Count,{0}",
        "lang.current" to "Current Lanauge",
        "lang.en" to "English",
        "lang.system" to "System",
        "lang.zh" to "Chinese",
    )
}

object I18nZeal_zh {
    val map = mapOf(
        "app.name" to "热情国际化",
        "count" to "数,{0}",
        "lang.current" to "当前语言",
        "lang.en" to "英语",
        "lang.system" to "跟随系统",
        "lang.zh" to "中文",
    )
}

