import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.util.Locale

abstract class GenerateI18nKeysTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val inputFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @TaskAction
    fun generate() {
        val source = inputFile.get().asFile.readText()

        val keys = Regex("\"([A-Za-z_][A-Za-z0-9_.-]*)\"\\s+to")
            .findAll(source)
            .map { it.groupValues[1] }
            .distinct()
            .toList()

        val pkg = packageName.get()
        val cls = className.get()

        val content = buildString {
            appendLine("package $pkg")
            appendLine()
            appendLine("/**")
            appendLine(" * Auto generated by i18nZeal.")
            appendLine(" * Do not edit manually.")
            appendLine(" */")
            appendLine("object $cls {")

            keys.forEach { key ->
                appendLine("    const val ${key.toI18nKeyName()} = \"$key\"")
            }

            appendLine("}")
        }

        val outputFile = outputDir.get()
            .file("${pkg.replace('.', '/')}/$cls.kt")
            .asFile

        outputFile.parentFile.mkdirs()
        outputFile.writeText(content)
    }

    private fun String.toI18nKeyName(): String {
        val name = split("_", "-", ".")
            .filter { it.isNotBlank() }
            .mapIndexed { index, part ->
                if (index == 0) {
                    part.replaceFirstChar {
                        it.lowercase(Locale.ROOT)
                    }
                } else {
                    part.replaceFirstChar {
                        it.titlecase(Locale.ROOT)
                    }
                }
            }
            .joinToString("")

        return when {
            name.isBlank() -> "_"
            name.first().isDigit() -> "_$name"
            name in kotlinKeywords -> "${name}_"
            else -> name
        }
    }

    private val kotlinKeywords = setOf(
        "as", "break", "class", "continue", "do", "else", "false",
        "for", "fun", "if", "in", "interface", "is", "null",
        "object", "package", "return", "super", "this", "throw",
        "true", "try", "typealias", "typeof", "val", "var", "when", "while"
    )
}